name: Build, Test, and Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Compile the pipeline
        run: |
          python pipelines/compile_pipeline.py  # This compiles the pipeline to pipeline.json
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Replace with your secret containing the service account key JSON

      - name: Upload Pipeline to GCS
        run: |
          gsutil cp pipeline.json gs://bucketz1234nix/pipelines/  # Ensure pipeline.json exists

      - name: Submit Pipeline to Vertex AI
        run: |
          gcloud ai pipelines run \
            --region=us-central1 \
            --template-path=gs://your-bucket-name/pipelines/pipeline.json \
            --pipeline-root=gs://your-bucket-name/artifacts/
