name: Build, Test, and Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          version: latest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile pipeline
        run: |
          python pipelines/compile_pipeline.py

      - name: Upload Pipeline to GCS
        run: |
          gsutil cp pipeline.json gs://bucketz1234nix/pipelines/

      - name: Submit Pipeline to Vertex AI
        run: |
          gcloud beta ai pipelines run \
            --region=us-central1 \
            --template-path=gs://bucketz1234nix/pipelines/pipeline.json \
            --pipeline-root=gs://bucketz1234nix/artifacts/ \
            --quiet