name: Compile and Upload Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  compile_pipeline:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python
      with:
        python-version: '3.9'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Compile pipeline
      run: |
        python compile_pipeline.py  # Run the script to compile the pipeline

    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Use secrets for your GCP project ID
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}  # Use secrets for your GCP credentials JSON

    - name: Upload pipeline.json to GCS
      run: |
        gsutil cp pipeline.json gs://your-bucket-name/pipelines/  # Upload the pipeline JSON to your GCS bucket
